-- Empresa maestra (cod_empresa = 1, Digital Mind) y menú del dashboard.
--  * Los super administradores pertenecen a la empresa 1 (el login exige que exista y esté activa).
--  * tb_pagina_rol de la empresa 1 es la PLANTILLA de menú que se copia al crear empresas
--    (ver cl_empresas.php: "WHERE cod_empresa = 1 AND cod_rol IN(2,3,6)").
-- Datos personales y api_key van vacíos a propósito.

-- tb_empresas WHERE cod_empresa = 1 (1 filas)
INSERT IGNORE INTO `tb_empresas` (`cod_empresa`, `cod_tipo_empresa`, `cod_plan`, `ruc`, `nombre`, `alias`, `folder`, `direccion`, `telefono`, `correo`, `envio_grava_iva`, `representante_nombre`, `representante_documento`, `representante_celular`, `representante_correo`, `fecha_registro`, `fecha_caducidad`, `mensualidad`, `logo`, `logo_min`, `color`, `url_web`, `url_android`, `url_ios`, `facebook_pixel`, `facebook_pixel_verify`, `api_key`, `timezone`, `paginacion`, `impuesto`, `service_percentage`, `currency`, `datetime_format`, `cod_consumidor_final`, `programar_pedido`, `cant_dias_programar_pedido`, `fidelizacion`, `giftcard`, `estado`, `user_create`, `description`, `promo_text`, `keywords`, `front_header`, `front_menu`, `iniciar_en_menu`, `ambiente`, `hosting`, `recordar_ordenes`, `recordar_ordenes_tiempo`, `tipo_recorte`, `menu_type`, `is_emprendedor`, `stockExterno`, `is_delivery`, `is_pickup`, `is_insitu`, `front_product_card`, `cart_abandonment_minutes`, `cart_expiry_hours`, `cart_campaigns_enabled`, `cart_campaign_min_interval`, `cart_campaign_max`, `cart_recovery_email`, `cart_recovery_push`, `cart_recovery_whatsapp`, `tabs_order`, `mesa_tipo`, `prep_time_badge_minutes`) VALUES
    ('1', '3', '0', NULL, 'Digital Mind', 'digital-mind', '', NULL, '', NULL, '0', '', NULL, NULL, '', NULL, '2020-04-30', '0', 'logo.jpg', '', '#000000', 'https://digitalmindtec.com', NULL, NULL, '', '', '', '', '0', '12', '0', '', '', '0', '0', '5', '0', '0', 'A', '0', 'Desarrollo de páginas web, sistemas web y aplicaciones móviles', '', 'Digital, mind, desarrollo, web, app, ios, android, dm', 'RESTAURANTE', '', '0', 'development', '', '0', '30', 'square', 'list', '0', '0', '1', '1', '0', 'V2', '60', '72', '0', '60', '3', '0', '0', '0', NULL, 'NUMERO', '120');

-- tb_paginas (74 filas)
INSERT IGNORE INTO `tb_paginas` (`cod_pagina`, `cod_padre`, `id`, `icono`, `nombre`, `titulo`, `data_translate`, `posicion`, `estado`) VALUES
    ('1', '0', 'inicio', 'home', 'index.php', 'Inicio', 'menu-inicio', '1', 'A'),
    ('2', '0', 'menu-productos', 'coffee', '#', 'Productos', 'menu-productos', '3', 'A'),
    ('3', '2', 'productos-lista', '', 'productos.php', 'Lista', 'menu-lista', '1', 'A'),
    ('4', '2', 'productos-crear', '', 'crear_productos.php', 'Crear', 'menu-crear', '2', 'A'),
    ('5', '0', 'sucursales', 'clipboard', '#', 'Sucursales', 'menu-sucursales', '2', 'A'),
    ('6', '0', 'ordenes', 'shopping-cart', 'ordenes.php', 'Ordenes', 'menu-ordenes', '4', 'A'),
    ('7', '0', 'clientes', 'user', 'clientes.php', 'Clientes', 'menu-clientes', '5', 'A'),
    ('8', '0', 'usuarios', 'users', 'usuarios.php', 'Usuarios', 'menu-usuarios', '6', 'A'),
    ('9', '13', 'codigo-promocional', 'tag', 'codigo_promocional.php', 'Cupones', 'menu-codigo-promocional', '1', 'A'),
    ('10', '0', 'menu-categorias', 'grid', '#', 'Categor&iacute;as', 'menu-categorias', '1', 'A'),
    ('11', '10', 'categorias-lista', '', 'categorias.php', 'Lista', 'menu-lista', '1', 'A'),
    ('12', '10', 'categorias-crear', '', 'crear_categorias.php', 'Crear', 'menu-crear', '2', 'A'),
    ('13', '0', 'menu-marketing', 'gift', '#', 'Promociones', 'menu-marketing', '8', 'A'),
    ('14', '13', 'marketing-productos', '', 'promociones.php', 'Descuentos', 'menu-promociones', '2', 'A'),
    ('15', '13', 'marketing-envios', '', 'marketing_envios.php', 'Env&iacute;os', 'menu-envios', '3', 'A'),
    ('16', '2', 'productos-disponibilidad', '', 'gestion_disponibilidad_productos.php', 'Disponibilidad', 'menu-disponibilidad', '3', 'A'),
    ('17', '0', 'menu-delivery', 'truck', '#', 'Mis Motorizados', 'menu-delivery', '9', 'A'),
    ('18', '17', 'delivery-mapa', '', 'mapa_motorizado.php', 'Ubicaci&oacute;n', 'menu-ubicacion', '1', 'A'),
    ('19', '5', 'menu-disponibilidad', 'calendar', 'sucursal_festivos.php', 'Disponibilidad', 'menu-disponibilidad', '3', 'A'),
    ('20', '0', 'menu-web-items', 'trello', '#', 'M&oacute;dulos', 'menu-modulos', '11', 'A'),
    ('92', '36', 'facturas-pendientes', '', 'facturas_pendientes.php', 'Facturas', 'facturas-pendientes', '1', 'A'),
    ('22', '20', 'menu-web-banners', '', 'banners.php', 'Banners', 'menu-banners', '1', 'A'),
    ('23', '5', 'sucursales-lista', '', 'sucursales.php', 'Lista', 'menu-lista', '1', 'A'),
    ('24', '0', 'gestion-ordenes', 'shopping-bag', 'gestion_ordenes_v5.php', 'Gesti&oacute;n Ordenes', 'menu-gestion-ordenes', '4', 'A'),
    ('25', '0', 'menu-noticias', 'grid', '#', 'Noticias', 'menu-noticias', '1', 'A'),
    ('26', '25', 'noticias-lista', '', 'noticias.php', 'Lista', 'menu-lista', '2', 'A'),
    ('27', '25', 'noticias-crear', '', 'crear_noticia.php', 'Crear', 'menu-crear', '3', 'A'),
    ('28', '25', 'categorias_noticias', '', 'categorias_noticias.php', 'Categorias', 'menu-categorias', '1', 'A'),
    ('29', '20', 'notificaciones', '', 'notificaciones.php', 'Notificaciones', 'menu-notificaciones', '3', 'A'),
    ('30', '39', 'calificaciones', '', 'calificaciones.php', 'Experiencia del cliente', 'menu-calificaciones', '4', 'A'),
    ('31', '20', 'menu-configuraciones', '', 'configuraciones.php', 'Configuraciones', 'menu-configuraciones', '1', 'A'),
    ('32', '0', 'menu-empresas', 'grid', '#', 'Empresas', 'menu-empresas', '2', 'A'),
    ('33', '32', 'empresas-crear', '', 'crear_empresa.php', 'Crear', 'menu-crear', '2', 'A'),
    ('34', '32', 'empresas-lista', '', 'empresas.php', 'Lista', 'menu-lista', '1', 'A'),
    ('35', '5', 'sucursales-crear', '', 'crear_sucursales.php', 'Crear', 'menu-crear', '2', 'A'),
    ('36', '0', 'menu', 'home', '#', 'Integraciones', 'menu-integraciones', '1', 'A'),
    ('37', '36', 'app', 'grid', 'mi_app_motorizado.php', 'App Motorizado', 'menu-app-motorizado', '1', 'A'),
    ('39', '0', 'menu-reportes', 'trending-up', '#', 'Reportes', 'menu-reportes', '99', 'A'),
    ('40', '39', 'menu-reportes-ventas', '', 'reporte_ventas.php', 'Ventas', 'menu-reportes-ventas', '0', 'A'),
    ('41', '0', 'menu-ayuda', 'help-circle', '#', 'Ayuda', 'menu-ayuda', '999', 'A'),
    ('43', '41', 'menu-faq', '', 'FAQ.php', 'FAQ', 'menu-faq', '3', 'A'),
    ('46', '41', 'menu-crear-faq', '', 'crear_faq.php', 'Crear FAQ', 'menu-crear-faq', '4', 'A'),
    ('50', '2', 'productos-importar', '', 'importar_productos.php', 'Importar', 'menu-importar', '4', 'A'),
    ('51', '20', 'menu-tarjetas', '', 'lista_cards_fidelizacion.php', 'Tarjetas', 'menu-tarjetas', '1', 'A'),
    ('52', '39', 'reporte-usuarios-nivel', '', 'reporte_usuarios_nivel.php', 'Fidelizacion Usuarios', 'reporte-usuarios-nivel', '1', 'A'),
    ('56', '0', 'gestion-ordenes-v2', 'shopping-bag', 'gestion_ordenes_v5.php', 'Gesti&oacute;n Ordenes Deprecated', 'menu-gestion-ordenes-v2', '4', 'A'),
    ('57', '39', 'menu-reportes-ventas-diarios', '', 'reporte_diario.php', 'Ventas Diario', 'menu-reportes-ventas-diarios', '1', 'A'),
    ('82', '20', 'sugerencias-checkout', ' ', 'sugerencias_checkout.php', 'Sugerencias checkout', 'sugerencias-checkout', '2', 'A'),
    ('59', '13', 'cupones-clientes', 'tag', 'cupones.php', 'Cupones a clientes', 'menu-cupones-clientes', '1', 'A'),
    ('81', '0', 'gestion-ordenes-map', 'shopping-bag', 'gestion_ordenes_vmap.php', 'G. Ordenes Mapa', 'menu-gestion-ordenes-mapa', '4', 'A'),
    ('61', '36', 'menu-integracion-contifico', 'grid', 'rucs.php', 'Contífico', 'menu-integracion-contifico', '2', 'A'),
    ('62', '13', 'gift-cards', '', 'giftcards.php', 'Gift cards', 'gift-cards', '6', 'A'),
    ('63', '5', 'poligonos', '', 'poligonos.php', 'Cobertura', 'menu-cobertura', '3', 'A'),
    ('64', '17', 'crear-motorizados', '', 'flota.php', 'Crear y Lista', 'crear-motorizados', '1', 'A'),
    ('65', '39', 'menu-reportes-delivery', '', 'reporte_delivery.php', 'Delivery', 'menu-reportes-delivery', '0', 'A'),
    ('66', '0', 'ordenes-pos', 'shopping-cart', 'ordenes_pos.php', 'Órdenes Pos', 'menu-ordenes-pos', '88', 'A'),
    ('67', '5', 'sucursales-costo', '', 'sucursales_costo_envio.php', 'Costo envío', 'menu-costo', '3', 'A'),
    ('68', '20', 'editar-pagina', '', 'editar_pagina.php', 'Mi Página', 'editar-pagina', '1', 'A'),
    ('69', '20', 'orden-cuponera', '', 'ordenes_cuponera.php', 'Cupones por compra', 'orden-cuponera', '999', 'A'),
    ('70', '39', 'menu-reportes-delivery-courier', '', 'reporte_courier.php', 'Delivery por Courier', 'menu-reportes-delivery-courier', '4', 'A'),
    ('71', '0', 'menu-flota', 'grid', '#', 'Flota', 'menu-flota', '1', 'A'),
    ('79', '0', 'gestion-flota', 'shopping-bag', 'flota_gestion_2.php', 'Mis entregas', 'menu-flota', '4', 'A'),
    ('80', '39', 'reporte-flota', '', 'reporte_flotas.php', 'Flotas', '', '8', 'A'),
    ('74', '0', 'menu-flota', 'grid', '#', 'Flota', 'menu-flota', '1', 'A'),
    ('77', '71', 'flota-lista', '', 'flota.php', 'Lista', 'menu-lista', '1', 'A'),
    ('83', '39', 'reporte-producto-mas-vendido', '', 'reporte_productos_mas_vendidos.php', 'Producto más vendido', '', '9', 'A'),
    ('84', '0', 'eventos', 'calendar', 'ordenes-eventos.php', 'Eventos', '', '9', 'A'),
    ('85', '39', 'mapa-calor', '', 'reporte_mapa_calor.php', 'Mapa de Calor', '', '9', 'A'),
    ('86', '71', 'flota-historico', '', 'flota_ordenes_historico.php', 'Histórico', 'menu-historico', '2', 'A'),
    ('87', '13', 'first-purchase', '', 'promocion_producto_gratis.php', 'Primera Compra', 'first-purchase', '3', 'A'),
    ('88', '39', 'reporte_tiempo_aceptacion', '', 'reporte_tiempo_aceptacion.php', 'Tiempo aceptación', 'reporte_tiempo_aceptacion', '1', 'A'),
    ('89', '39', 'reporte_tiempos_motorizado', '', 'reporte_tiempos_motorizado.php', 'Tiempo carrera', 'reporte_tiempos_motorizado', '2', 'A'),
    ('90', '39', 'reporte_pedidos_programados', '', 'reporte_pedidos_programados.php', 'Pedidos programados', 'reporte_pedidos_programados', '3', 'A'),
    ('91', '39', 'menu-carritos-abandonados', '', 'reporte_carritos_abandonados.php', 'Carritos Abandonados', 'menu-carritos-abandonados', '0', 'A');

-- tb_pagina_rol WHERE cod_empresa = 1 (56 filas)
INSERT IGNORE INTO `tb_pagina_rol` (`cod_pagina_rol`, `cod_pagina`, `cod_rol`, `cod_empresa`, `posicion`) VALUES
    ('311', '32', '1', '1', '2'),
    ('312', '33', '1', '1', '4'),
    ('313', '34', '1', '1', '3'),
    ('315', '1', '2', '1', '1'),
    ('4883', '35', '2', '1', '12'),
    ('4881', '5', '2', '1', '3'),
    ('4882', '23', '2', '1', '11'),
    ('4880', '12', '2', '1', '18'),
    ('4879', '11', '2', '1', '17'),
    ('4878', '10', '2', '1', '16'),
    ('1037', '41', '1', '1', '5'),
    ('1040', '43', '1', '1', '9'),
    ('1041', '46', '1', '1', '8'),
    ('4884', '19', '2', '1', '10'),
    ('2015', '1', '1', '1', '1'),
    ('4885', '63', '2', '1', '13'),
    ('4886', '2', '2', '1', '4'),
    ('4887', '3', '2', '1', '7'),
    ('4888', '4', '2', '1', '8'),
    ('4889', '16', '2', '1', '9'),
    ('4890', '6', '2', '1', '5'),
    ('4891', '24', '2', '1', '6'),
    ('4892', '7', '2', '1', '14'),
    ('4893', '8', '2', '1', '15'),
    ('4894', '13', '2', '1', '19'),
    ('4895', '9', '2', '1', '20'),
    ('4896', '14', '2', '1', '21'),
    ('4897', '20', '2', '1', '2'),
    ('4898', '22', '2', '1', '22'),
    ('4899', '31', '2', '1', '23'),
    ('4900', '39', '2', '1', '24'),
    ('4901', '40', '2', '1', '25'),
    ('4902', '1', '3', '1', '1'),
    ('4904', '2', '3', '1', '2'),
    ('4905', '3', '3', '1', '3'),
    ('4906', '4', '3', '1', '4'),
    ('4907', '16', '3', '1', '5'),
    ('4908', '6', '3', '1', '6'),
    ('4909', '24', '3', '1', '7'),
    ('4910', '7', '3', '1', '8'),
    ('4911', '8', '3', '1', '9'),
    ('4912', '1', '4', '1', '1'),
    ('4913', '2', '4', '1', '2'),
    ('4914', '16', '4', '1', '3'),
    ('4915', '6', '4', '1', '5'),
    ('4916', '24', '4', '1', '4'),
    ('4951', '1', '5', '1', '1'),
    ('4952', '5', '5', '1', '5'),
    ('4953', '19', '5', '1', '6'),
    ('4954', '2', '5', '1', '3'),
    ('4955', '16', '5', '1', '4'),
    ('4956', '24', '5', '1', '2'),
    ('7777', '25', '2', '1', '99'),
    ('7778', '28', '2', '1', '99'),
    ('7779', '26', '2', '1', '99'),
    ('7780', '27', '2', '1', '99');
