window.APP_CONFIG = {
    VITE_APP_TITLE:"Kuno Seafood",
    VITE_API_KEY: "API-kuno-seafood-EZ9L9C4PEO5EU76",
    VITE_COLOR_PRIMARY: "#014B81",
    VITE_PIXEL_FACEBOOK: "",
    VITE_PRODUCT_ITEM_VERSION: "V2",
    VITE_PAGE_INITIAL_HOME: 1,
    VITE_WELCOME_IMAGE: 0,
    VITE_LOGO_RECTANGLE: 1
};